services:
  nginx:
    platform: linux/amd64
    image: nginx-rift-ctf
    build:
      context: .
      dockerfile: Dockerfile.ctf
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    init: true
    ports:
      - "19321:19321"
      - "19324:19324"
    tty: true
    stdin_open: true
