load_module /nginx-src/objs/ngx_http_js_module.so;

daemon off;
user ubuntu;
worker_processes 1;
error_log stderr info;
pid tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    access_log off;
    js_import njs_fetch_proxy from njs-fetch-proxy.js;

    server {
        listen 19411;
        server_name localhost;

        location / {
            return 200 "njs fetch proxy lab ok\n";
        }

        location /dynamic_proxy {
            js_fetch_proxy http://$arg_u:$arg_p@127.0.0.1:19412;
            js_content njs_fetch_proxy.http_fetch;
        }
    }

    server {
        listen 19412;
        server_name proxy.local;

        location /origin {
            js_content njs_fetch_proxy.proxy_endpoint;
        }
    }

    server {
        listen 19413;
        server_name origin.local;

        location /origin {
            js_content njs_fetch_proxy.origin_endpoint;
        }
    }
}
